"""Userfield

Revision ID: 437ccbbf677c
Revises: 077dfdcc0ffa
Create Date: 2022-01-19 15:49:28.476616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437ccbbf677c'
down_revision = '077dfdcc0ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('prefix', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'prefix')
    op.drop_column('users', 'country')
    op.drop_column('users', 'cp')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
